version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd "To-do-List"
      - npm install --save --legacy-peer-deps
      - npm install -g @angular/cli
      - npm install --save bootstrap
      - npm audit fix --force
      - Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted
  build:
    commands:
      - echo "Build a to-do list project..."
      - ng build --configuration production
  post_build:
    commands:
      - echo "updating files in the S3 bucket..."
      - aws s3 sync dist/to-do-list/ s3://angular-todolist-06152023 --delete