version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli
      - ng add @ng-bootstrap/schematics
  build:
    commands:
      - echo "Build a to-do list project..."
      - ng build --configuration production
  post_build:
    commands:
      - echo "updating files in the S3 bucket..."
      - aws s3 sync dist/to-do-list/ s3://angular-todolist-06152023 --delete